---
- name: Instalar servidor web
  dnf:
    name: "{{ web_server_package }}"
    state: present

- name: Iniciar servicio web
  service:
    name: "{{ web_server_package }}"
    state: started
    enabled: true

- name: Desplegar pagina web
  copy:
    content: "<h1>CaribeXperience - Configurado con Ansible</h1>"
    dest: /var/www/html/index.html
    mode: "0644"